data:
  compute_svd: 5

model:
  name: treba
  z_dim: 32
  h_dim: 256
  rnn_dim: 256
  num_layers: 1
  state_dim: 33
  action_dim: 33
  recurrent: True

train:
  start_epoch: 0
  batch_size: 512
  num_epochs_til_val: 10
  learning_rate: 0.0002
  num_epochs: 300
  clip: 10
  project_name: 'baseline'

log:
  basedir: tvae
